services:
  - type: web
    name: kristalball-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false  # You'll need to set this manually with your MongoDB Atlas URI
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://kristalball-frontend.vercel.app  # Update this after frontend deployment
